<?xml version="1.0" ?>
<robot name="yardguard" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="base_length" value="0.288" />
  <xacro:property name="base_width" value="0.24" />
  <xacro:property name="base_height" value="0.15" />

  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_length" value="0.05" />

  <!-- base_footprint (projection of base_link on the ground) -->
  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${wheel_radius + 0.035}"/>
  </joint>
  <!-- base_link and base_scan (required for Nav2) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height} "/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </collision>
    <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
  </link>
  <!-- <joint name="base_scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin rpy="0 0 0" xyz="-0.043199999999999995 0 0.075"/>
  </joint>
  <link name="base_scan">
    <visual>
      <geometry>
        <cylinder length="0.0275" radius="0.035"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="grey"/>
    </visual>
  </link> -->
  <!-- Wheels (2 differential wheels + 1 caster wheel to keep the balance) -->
  <joint name="back_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin rpy="0 0 0" xyz="-0.13 0.155 -0.045"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}"
                            o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
  </link>
  <joint name="back_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin rpy="0 0 0" xyz="-0.13 -0.155 -0.045"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}"
                            o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
  </link>
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin rpy="0 0 0" xyz="0.13 -0.155 -0.045"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}"
                            o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
  </link>
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin rpy="0 0 0" xyz="0.13 0.155 -0.045"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}"
                            o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
  </link>
</robot>
